### PR TITLE
Prepare for fork

### LINKED ISSUE #2: Convert repo into a fork of chatterbox

### PR DESCRIPTION
**Pull request by psrpinto**
Related to #2
This will require changes in the chatrix WordPress plugin: https://github.com/Automattic/chatrix/pull/63

This PR undoes unnecessary changes to chatterbox, so that only changes required for our custom functionality are present. Once this PR is merged, we'll be one step closer to turning this repo into a fork of chatterbox.

### CODE REVIEW

**Review by ashfame — COMMENTED** [review]
I don't think it's possible to actually review the code changes in this PR by just looking at it. I trust you to have done the changes correctly and anything that we do miss can be handled later on.

I am wondering about the direction though. Wouldn't it have been simpler to fork chatrix first and then apply our customizations on top of it? With the current approach, we can't have the same commit history for Chatterbox until the point of fork, and that sounds like more complications down the road?

**Comment by akirk** [comment]
You can use these commands to compare it with https://github.com/vector-im/chatterbox/

```
git pull origin
git checkout cae8e98987d6b78915723c98a659eb33ef27e5f2 # last commit on chatterbox
git co -b upstream-main # create a local branch where we'll fetch the changes from there going forward
git remote add upstream git@github.com:vector-im/chatterbox.git
git branch --set-upstream-to=upstream/main upstream-main
git pull upstream-main
git diff prepare-for-fork # compare against this branch
```

**Comment by ashfame** [comment]
Yeah, it's certainly possible to compare the state between any two commits. Are we using this approach just to generate a diff over on top of upstream commits? Or we would maintain the fork this way only?

**Review by akirk — APPROVED** [review]
Thanks for this!

**Review by ashfame — APPROVED** [review]
Thanks for taking care of this!

**Pull request merged**
